# Generated by Django 4.0.2 on 2022-05-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halalan2022', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
