# Generated by Django 4.0.2 on 2022-05-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halalan2022', '0004_alter_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(),
        ),
    ]
