# Generated by Django 4.0.2 on 2022-05-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halalan2022', '0011_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
