# Generated by Django 4.0.2 on 2022-05-17 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halalan2022', '0014_alter_user_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
    ]
