# Generated by Django 4.0.2 on 2022-05-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halalan2022', '0015_remove_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
