# Generated by Django 4.0.2 on 2022-05-17 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halalan2022', '0018_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
