# Generated by Django 4.0.2 on 2022-05-18 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('halalan2022', '0019_rename_user_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halalan2022.users', unique=True),
        ),
    ]
