# Generated by Django 4.0.2 on 2022-05-18 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('halalan2022', '0020_alter_vote_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='candidate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halalan2022.candidate', unique=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halalan2022.users'),
        ),
    ]
